//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MicroClient.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_MICROCTYPE                  129
#define IDD_DIALOG1                     130
#define IDC_TEAM                        1000
#define IDC_SERVER                      1001
#define IDC_CHANNEL                     1002
#define ID_CONNECT                      32771
#define ID_DISCONNECT                   32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
